#!/bin/sh /etc/rc.common
# Copyright (C) 2022 Artel Video Systems

START=70
STOP=20

AVSPROGRAM=avsProcessOG
AVSPATH=/usr/artel/bin
AVSARGS="--daemon"
AVSDBGFPGA=/usr/artel/config/fpgadebug
KILLME=/usr/bin/killall
BT=`/usr/artel/bin/getBoardType`
BoardType=$?
FT=`/usr/artel/bin/getFPGAType`
FPGAType=$?

if [ -f $AVSDBGFPGA ]
then
    echo "DEBUG MODE - Do not start avsProcess"
    exit 0
fi

if [ $BoardType == 75 ] 
then
    echo "DO NOT start avsProcess - BrdType $BoardType "
    exit 0
fi


start() {
     echo -n "Starting avsProcess..."
         start-stop-daemon -S -a $AVSPROGRAM -x $AVSPATH/$AVSPROGRAM -- $AVSARGS 
     echo "done"
            
}

stop() {
     echo -n "Shutting down AVS process..."
         $KILLME avsProcessOG
     echo "done"
}
