#!/bin/sh /etc/rc.common
# Copyright (C) 2022 Artel Video Systems

START=20

AVSPATH=/usr/artel/bin
AVSDBGFPGA=/usr/artel/config/fpgadebug

BT=`/usr/artel/bin/getBoardType`
BoardType=$?
FT=`/usr/artel/bin/getFPGAType`
FPGAType=$?


start() {
    echo -n "Initializing CAN network interface..."
    $AVSPATH/startcan.sh
    echo "done."
if [ -f $AVSDBGFPGA ]
then
    echo "DEBUG MODE - Do not load FPGA"
    exit 0
fi

if [ $BoardType == 75 ] 
then
    echo "DO NOT load FPGA - BrdType $BoardType "
    exit 0
fi

            echo -n "Program Si5338..."
            $AVSPATH/prog5338
            echo "done."
            echo -n "Loading FPGA image..."
            $AVSPATH/loadfpga.sh avsOGLoadLink
            echo "done."
            echo -n "Loading FPGA PCI driver modules..."
            $AVSPATH/loadaxi.sh
            echo "done."
            
}
	
